"""Public sparse-MLA integration surface."""

from __future__ import annotations

from b12x.attention.mla import (
    B12XAttentionArena,
    B12XAttentionArenaCaps,
    CompressedMLACoreInputs,
    MLASparseDecodeMetadata,
    MLASparseExtendMetadata,
    B12XAttentionWorkspace,
    B12XAttentionWorkspaceContract,
    COMPRESSED_MLA_C128_PAGE_SIZE,
    COMPRESSED_MLA_C4_PAGE_SIZE,
    COMPRESSED_MLA_HEAD_DIM,
    COMPRESSED_MLA_INDEX_TOPK,
    COMPRESSED_MLA_LOCAL_Q_HEADS_TP2,
    COMPRESSED_MLA_NOPE_DIM,
    COMPRESSED_MLA_ROPE_DIM,
    COMPRESSED_MLA_SWA_PAGE_SIZE,
    COMPRESSED_MLA_SWA_TOKENS,
    clear_mla_caches,
    compressed_mla_decode_forward,
    dense_mla_reference,
    compressed_mla_page_nbytes,
    compressed_sparse_mla_reference,
    gather_compressed_mla_kv_cache_reference,
    pack_mla_kv_cache_reference,
    pack_compressed_mla_kv_cache_reference,
    prepare_compressed_mla_core_inputs,
    sparse_mla_decode_forward,
    sparse_mla_reference,
    sparse_mla_extend_forward,
    unpack_mla_kv_cache_reference,
    unpack_compressed_mla_kv_cache_reference,
)

__all__ = [
    "B12XAttentionArena",
    "B12XAttentionArenaCaps",
    "B12XAttentionWorkspace",
    "B12XAttentionWorkspaceContract",
    "COMPRESSED_MLA_C128_PAGE_SIZE",
    "COMPRESSED_MLA_C4_PAGE_SIZE",
    "COMPRESSED_MLA_HEAD_DIM",
    "COMPRESSED_MLA_INDEX_TOPK",
    "COMPRESSED_MLA_LOCAL_Q_HEADS_TP2",
    "COMPRESSED_MLA_NOPE_DIM",
    "COMPRESSED_MLA_ROPE_DIM",
    "COMPRESSED_MLA_SWA_PAGE_SIZE",
    "COMPRESSED_MLA_SWA_TOKENS",
    "CompressedMLACoreInputs",
    "MLASparseDecodeMetadata",
    "MLASparseExtendMetadata",
    "clear_mla_caches",
    "compressed_mla_decode_forward",
    "dense_mla_reference",
    "compressed_mla_page_nbytes",
    "compressed_sparse_mla_reference",
    "gather_compressed_mla_kv_cache_reference",
    "pack_mla_kv_cache_reference",
    "pack_compressed_mla_kv_cache_reference",
    "prepare_compressed_mla_core_inputs",
    "sparse_mla_decode_forward",
    "sparse_mla_reference",
    "sparse_mla_extend_forward",
    "unpack_mla_kv_cache_reference",
    "unpack_compressed_mla_kv_cache_reference",
]
